import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: ['src/index.ts'],
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: true,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk'],
  },
  {
    entry: { 'anthropic-memory/index': 'src/adapters/anthropic-memory/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk'],
  },
  {
    entry: { 'letta/index': 'src/adapters/letta/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk', '@letta-ai/letta-client'],
  },
  {
    entry: { 'mastra/index': 'src/adapters/mastra/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk', '@mastra/core', '@mastra/memory'],
  },
  {
    entry: { 'mem0/index': 'src/adapters/mem0/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk', 'mem0ai'],
  },
  {
    entry: { 'langchain/index': 'src/adapters/langchain/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk', '@langchain/core', '@langchain/community'],
  },
  {
    entry: { 'langgraph/index': 'src/adapters/langgraph/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: [
      'better-sqlite3',
      '@anthropic-ai/sdk',
      '@langchain/langgraph',
      '@langchain/langgraph-checkpoint',
    ],
  },
  {
    entry: { 'gbrain/index': 'src/adapters/gbrain/index.ts' },
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: false,
    target: 'node20',
    external: ['better-sqlite3', '@anthropic-ai/sdk', 'gbrain'],
  },
  {
    entry: ['src/cli.ts'],
    format: ['esm'],
    dts: false,
    sourcemap: true,
    clean: false,
    target: 'node20',
    banner: {
      js: '#!/usr/bin/env node',
    },
    external: ['better-sqlite3', '@anthropic-ai/sdk'],
  },
]);
